name: ODFE CLI Test
on: [pull_request, push]

jobs:
  test:
    defaults:
      run:
        working-directory: odfe-cli
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go ubuntu-latest
        uses: actions/setup-go@v2
        with:
          go-version: 1.14

      - name: Check out AD CLI
        uses: actions/checkout@v2

      - name: Format
        run: |
          cd ..
          go get golang.org/x/tools/cmd/goimports
          cd odfe-cli
          goimports -w .
      - name: Check for modified files
        id: git-check
        run: |
          echo ::set-output name=modified::$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)
      - name: Display unformated changes and fail if any
        if: steps.git-check.outputs.modified == 'true'
        run: |
          echo "Failed to format using goimports. Use `goimports -w .` and ammend commit".
          git diff
          exit 1
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v1
        with:
          version: v1.28
          working-directory: odfe-cli
      - name: Run Test
        env:
          GOPROXY: "https://proxy.golang.org"
        run: |
          go test ./...